services: 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - "5000:5000"

    environment:
      REACT_APP_API_URL: http://localhost:5000

    depends_on:
      - server 
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment: 
      PORT: 3001
      MONGO_USERNAME: admin
      MONGO_PASSWORD: csse4103
      MONGO_DATABASE: postitdb

networks:
  app-network:
    driver: bridge


    